version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db-bank_as
    networks:
      - best_bank_as_network
    env_file: .env
    volumes:
      - .:/app
    restart: always
  
  db-bank_as:
    container_name: db-bank_as
    image: postgres:latest
    ports:
      - 5438:5432
    volumes:
      - bank_as_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bank_as-db
      - POSTGRES_USER=bank_as-user
      - POSTGRES_PASSWORD=password
    networks:
      - best_bank_as_network

networks:
  best_bank_as_network:
    name: best_bank_as_network

volumes:
  bank_as_data: