version: "3.9"

services:
    db:
        image: postgres:13-alpine
        volumes:
            - db_data:/var/lib/postgresql/data/
        env_file:
            - db_${RTE}.env

    app:
        build: .
        env_file:
            - db_${RTE}.env
        volumes:
            - .:/app/
            - static:/static/
            - media:/media/
        depends_on:
            - db

    nginx:
        build: nginx/
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./nginx/${RTE}/conf.d/:/etc/nginx/conf.d/
            - ./certs/:/etc/letsencrypt/
            - static:/static/
            - media:/media/
        depends_on:
            - app

volumes:
    db_data:
    static:
    media:
