version: "3.9"

services:
    db:
        image: postgres:13-alpine
        volumes:
            - db_data:/var/lib/postgresql/data/
        env_file:
            - db_${RTE}.env
        ports:
        - 5438:5432

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
    app:
        build: .
        env_file:
            - db_${RTE}.env
        volumes:
            - .:/app/
            - static:/static/
            - media:/media/
        depends_on:
            - db
            - redis

    nginx:
        build: nginx/
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./nginx/${RTE}/conf.d/:/etc/nginx/conf.d/
            - ./certs/:/etc/letsencrypt/
            - static:/static/
            - media:/media/
        depends_on:
            - app
    worker:
        build: .
        command: python manage.py rqworker default
        env_file:
            - db_${RTE}.env
        environment:
            - CONTAINER_ROLE=worker
        depends_on:
            - db
            - redis
volumes:
    db_data:
    static:
    media:
    redis_data:
