# Generated by Django 4.2.5 on 2023-10-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                editable=False,
            ),
        ),
    ]
