# Generated by Django 4.2.5 on 2024-01-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Processed"), (3, "Rejected")], default=1
            ),
        ),
    ]
