# Generated by Django 4.2.5 on 2023-09-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('best_bank_as', '0002_customerlevel_remove_customer_customer_level_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_level',
        ),
    ]
