# Generated by Django 4.2.5 on 2023-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0002_customer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_status",
            field=models.IntegerField(
                choices=[(1, "Active"), (2, "Inactive")], default=0
            ),
        ),
    ]
