# Generated by Django 4.2.5 on 2024-01-19 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("best_bank_as", "0003_account_account_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "In Progress"), (2, "Paid"), (3, "Aborted")],
                        default=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="account",
            name="account_status",
            field=models.IntegerField(
                choices=[
                    (1, "Active"),
                    (2, "Inactive"),
                    (3, "Pending"),
                    (4, "Rejected"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")], default=1
            ),
        ),
        migrations.DeleteModel(
            name="CustomerApplication",
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="best_bank_as.customer",
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="employee_approved",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="supervisor_approved",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="best_bank_as.customer",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="best_bank_as.loanapplication",
            ),
        ),
    ]
