# Generated by Django 4.2.5 on 2023-09-22 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('best_bank_as', '0003_remove_customer_customer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='best_bank_as.customerlevel'),
            preserve_default=False,
        ),
    ]
