# Generated by Django 4.2.5 on 2024-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0004_alter_account_account_status_alter_customer_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reg_number", models.CharField(max_length=4, unique=True)),
                ("bank_name", models.CharField(max_length=255)),
                ("branch_name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
