# Generated by Django 4.2.5 on 2024-01-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "best_bank_as",
            "0004_loan_loanapplication_alter_account_account_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Employee Approved"),
                    (3, "Supervisor Approved"),
                    (4, "Rejected"),
                ],
                default=1,
            ),
        ),
    ]
