# Generated by Django 4.2.5 on 2023-09-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('best_bank_as', '0004_customer_customer_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='account_number1',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='account_number2',
        ),
        migrations.AddField(
            model_name='ledger',
            name='account_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='best_bank_as.account'),
            preserve_default=False,
        ),
    ]
