# Generated by Django 4.2.5 on 2024-01-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0006_ledger_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Processed"), (3, "Rejected")], default=0
            ),
        ),
    ]
