# Generated by Django 4.2.5 on 2024-01-21 21:45

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0006_delete_accounttype_remove_account_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="loan",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 20, 21, 45, 57, 455678, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
