# Generated by Django 4.2.5 on 2024-01-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0007_ledger_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="registration_number",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="best_bank_as.bank",
            ),
        ),
    ]
