# Generated by Django 4.2.5 on 2023-09-23 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0007_transaction_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="account_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="accounttype",
            old_name="account_type_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="customer_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="customerlevel",
            old_name="customer_level_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="ledger",
            old_name="ledger_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_id",
            new_name="id",
        ),
    ]
