# Generated by Django 4.2.5 on 2024-01-21 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0008_remove_account_account_number_alter_loan_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="end_date",
        ),
    ]
