# Generated by Django 4.2.5 on 2024-01-21 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("best_bank_as", "0009_remove_loan_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="best_bank_as.customer",
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="best_bank_as.customer",
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="employee_approved",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="supervisor_approved",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
