# Generated by Django 4.2.5 on 2024-01-21 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0010_alter_account_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="best_bank_as.account",
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="best_bank_as.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="best_bank_as.customer",
            ),
        ),
    ]
