# Generated by Django 4.2.5 on 2024-01-22 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0004_alter_account_account_status_alter_customer_status"),
        ("best_bank_as", "0011_alter_ledger_account_alter_ledger_transaction_and_more"),
    ]

    operations = []
