# Generated by Django 4.2.5 on 2024-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0012_merge_20240122_1850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_status",
            field=models.IntegerField(
                choices=[
                    (1, "Active"),
                    (2, "Inactive"),
                    (3, "Pending"),
                    (4, "Rejected"),
                ],
                default=2,
            ),
        ),
    ]
