# Generated by Django 4.2.5 on 2024-01-22 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("best_bank_as", "0008_alter_ledger_registration_number"),
        ("best_bank_as", "0013_alter_account_account_status"),
    ]

    operations = []
