name: Deploy Django Application

on:
  push:
    branches:
      - main
      - deploy-project

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: RTE, DJANGO_SECRET_KEY, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
          script: |
            cd projects/best-bank-as
            docker-compose -f docker-compose.yml up --build -d
        